### ISSUE TITLE
Improved Eureka integration and demo

### ISSUE THREAD

**Issue by JonathanGiles** [JonathanGiles/aspire4j#7]
Currently the storage-explorer demo requires the application.yml file to have the following configuration:

```yml
eureka:
  client:
    serviceUrl:
      defaultZone: ${services__eureka__https__0}/eureka/
  instance:
    preferIpAddress: true
```

This is reading `services__eureka__https__0` from the env vars specified by Aspire4j. It would be nice if the name were more Spring-friendly, or if there were a better way of wiring the storage explorer microservices in to eureka.
